# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104mR766UVLsluBrcca1f3hDHajNSebVR
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd

file_path = "/content/drive/MyDrive/job_dataset/Job_dataset.csv"

jobs = pd.read_csv(file_path)

jobs.head()

jobs.shape

jobs.columns

jobs.info()

for i in range(10):
    print(jobs["Skills"].iloc[i])
    print()

def extract_skills(text):

    text = str(text)

    found_skills = []

    # Match longer skill names first
    sorted_skills = sorted(
        skill_list,
        key=len,
        reverse=True
    )

    for skill in sorted_skills:

        if skill.lower() in text.lower():
            found_skills.append(skill)

    return found_skills

skills_list = [
    "MS-Office",
    "MS-Excel",
    "Data entry",
    "English Proficiency (Spoken)",
    "English Proficiency (Written)",
    "Negotiation",
    "Digital Marketing",
    "Market research",
    "Marketing Strategies",
    "Presentation skills",
    "Kannada Proficiency (Spoken)",
    "Interpersonal skills",
    "Effective Communication",
    "Legal Research",
    "Company Law",
    "Legal Drafting",
    "Statutory compliances",
    "Legal Writing",
    "Contract Management",
    "Accounting",
    "Tally",
    "MS-PowerPoint",
    "Leadership",
    "Team Management",
    "E-commerce",
    "Data Analytics",
    "Mentorship",
    "B2B Sales",
    "Lead Generation",
    "Sales Management",
    "Sales",
    "Problem Solving"
]

def extract_skills(text):
    text = str(text).lower()
    found_skills = []

    for skill in skills_list:
        if skill.lower() in text:
            found_skills.append(skill)

    return found_skills


jobs["Skills_List"] = jobs["Skills"].apply(extract_skills)

jobs[["Skills", "Skills_List"]].head(10)

jobs["Job_ID"] = range(1, len(jobs) + 1)

skills_table = jobs[["Job_ID", "Skills_List"]].explode("Skills_List")

skills_table = skills_table.rename(
    columns={"Skills_List": "Skill"}
)

skills_table = skills_table.dropna(subset=["Skill"])

skills_table = skills_table.reset_index(drop=True)

skills_table.head(20)

skills_table["Skill"].value_counts().head(20)

jobs[jobs["Skills"].str.contains(
    r"\+2 more",
    case=False,
    na=False
)][["Job_ID", "Skills"]].head(20)

jobs["Skills"].str.contains(
    r"\+2 more",
    case=False,
    na=False
).sum()

jobs["Hidden_Skills_Count"] = jobs["Skills"].str.count(r"\+2 more") * 2

jobs["Hidden_Skills_Count"].value_counts()

skills_table.head()

skills_table.shape

jobs.to_csv(
    "/content/drive/MyDrive/job_dataset/jobs_clean.csv",
    index=False
)

skills_table.to_csv(
    "/content/drive/MyDrive/job_dataset/skills_table.csv",
    index=False
)

!pip install duckdb

import duckdb

con = duckdb.connect()

con.register("jobs", jobs)
con.register("skills", skills_table)

con.sql("""
SELECT *
FROM jobs
LIMIT 10
""")

con.sql("""
SELECT
    Skill,
    COUNT(*) AS Job_Count
FROM skills
GROUP BY Skill
ORDER BY Job_Count DESC
LIMIT 10
""")

con.sql("""
SELECT
    "Company Name",
    COUNT(*) AS Job_Count
FROM jobs
GROUP BY "Company Name"
ORDER BY Job_Count DESC
LIMIT 10
""")

import re

def extract_salary(salary):
    numbers = re.findall(r'\d[\d,]*', str(salary))
    numbers = [int(x.replace(",", "")) for x in numbers]

    if len(numbers) >= 2:
        minimum = numbers[0]
        maximum = numbers[1]
    elif len(numbers) == 1:
        minimum = numbers[0]
        maximum = numbers[0]
    else:
        minimum = None
        maximum = None

    return pd.Series([minimum, maximum])


jobs[["Salary_Min", "Salary_Max"]] = jobs["Salary"].apply(extract_salary)

jobs["Salary_Avg"] = (
    jobs["Salary_Min"] + jobs["Salary_Max"]
) / 2

jobs["Salary_Avg_LPA"] = jobs["Salary_Avg"] / 100000

jobs[[
    "Salary",
    "Salary_Min",
    "Salary_Max",
    "Salary_Avg_LPA"
]].head(10)

con.unregister("jobs")
con.register("jobs", jobs)

con.sql("""
SELECT
    Locations,
    ROUND(AVG(Salary_Avg_LPA), 2) AS Avg_Salary_LPA,
    COUNT(*) AS Job_Count
FROM jobs
GROUP BY Locations
ORDER BY Avg_Salary_LPA DESC
""")

con.sql("""
SELECT
    "Company Name",
    COUNT(*) AS Job_Count
FROM jobs
GROUP BY "Company Name"
ORDER BY Job_Count DESC
LIMIT 10
""")

con.sql("""
SELECT
    Experience_Years,
    COUNT(*) AS Job_Count,
    ROUND(AVG(Salary_Avg_LPA), 2) AS Avg_Salary_LPA
FROM jobs
GROUP BY Experience_Years
ORDER BY Experience_Years
""")





jobs["Experience_Years"] = (
    jobs["Experience"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(int)
)

# Create Experience_Years
jobs["Experience_Years"] = (
    jobs["Experience"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(int)
)

# Refresh DuckDB table
try:
    con.unregister("jobs")
except:
    pass

con.register("jobs", jobs)

# Check columns DuckDB can see
print(con.sql("DESCRIBE jobs"))

con.sql("""
SELECT
    Experience_Years,
    COUNT(*) AS Job_Count,
    ROUND(AVG(Salary_Avg_LPA), 2) AS Avg_Salary_LPA
FROM jobs
GROUP BY Experience_Years
ORDER BY Experience_Years
""")

con.sql("""
SELECT
    "Company Name",
    COUNT(*) AS Job_Count
FROM jobs
GROUP BY "Company Name"
ORDER BY Job_Count DESC
LIMIT 10
""")

con.sql("""
SELECT
    Skill,
    COUNT(*) AS Job_Count
FROM skills
GROUP BY Skill
ORDER BY Job_Count DESC
LIMIT 15
""")

con.sql("""
SELECT
    s.Skill,
    COUNT(*) AS Job_Count,
    ROUND(AVG(j.Salary_Avg_LPA), 2) AS Avg_Salary_LPA
FROM skills s
JOIN jobs j
    ON s.Job_ID = j.Job_ID
GROUP BY s.Skill
HAVING COUNT(*) >= 20
ORDER BY Job_Count DESC
LIMIT 15
""")

con.sql("""
SELECT
    COUNT(*) AS Total_Jobs,
    COUNT(DISTINCT "Company Name") AS Total_Companies,
    COUNT(DISTINCT Locations) AS Total_Locations,
    ROUND(AVG(Salary_Avg_LPA), 2) AS Overall_Avg_Salary_LPA
FROM jobs
""")

con.sql("""
SELECT
    Locations,
    COUNT(*) AS Job_Count
FROM jobs
GROUP BY Locations
ORDER BY Job_Count DESC
""")

jobs.to_csv(
    "/content/drive/MyDrive/job_dataset/jobs_clean.csv",
    index=False
)

skills_table.to_csv(
    "/content/drive/MyDrive/job_dataset/skills_table.csv",
    index=False
)

print("Files saved successfully!")